// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3vvrHBhPOtW-U-4uFbMEWEWiW8RxIt8U',
    appId: '1:937322001415:web:bad652a2f2698c6534e6a2',
    messagingSenderId: '937322001415',
    projectId: 'ilycode2',
    authDomain: 'ilycode2.firebaseapp.com',
    storageBucket: 'ilycode2.firebasestorage.app',
    measurementId: 'G-ZQKQR5Z0L7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKmC4bx22znvB6yVgvUOcXg7o_m3MKfYk',
    appId: '1:937322001415:android:0ca207694a153f3434e6a2',
    messagingSenderId: '937322001415',
    projectId: 'ilycode2',
    storageBucket: 'ilycode2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABv6QNZgkwoTgn6w74TFVEf2TJVkGJmbQ',
    appId: '1:937322001415:ios:206e35d7f56868bd34e6a2',
    messagingSenderId: '937322001415',
    projectId: 'ilycode2',
    storageBucket: 'ilycode2.firebasestorage.app',
    iosBundleId: 'com.example.flutterKmeansFotocopy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABv6QNZgkwoTgn6w74TFVEf2TJVkGJmbQ',
    appId: '1:937322001415:ios:206e35d7f56868bd34e6a2',
    messagingSenderId: '937322001415',
    projectId: 'ilycode2',
    storageBucket: 'ilycode2.firebasestorage.app',
    iosBundleId: 'com.example.flutterKmeansFotocopy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3vvrHBhPOtW-U-4uFbMEWEWiW8RxIt8U',
    appId: '1:937322001415:web:2491475b73e7bb2f34e6a2',
    messagingSenderId: '937322001415',
    projectId: 'ilycode2',
    authDomain: 'ilycode2.firebaseapp.com',
    storageBucket: 'ilycode2.firebasestorage.app',
    measurementId: 'G-7QGKWSC6BW',
  );

}